name: Deploy .NET 8 Project to windows
on:
  push:
    branches:
      - main
      - dev
      - master
jobs:
  deploy:
    runs-on: windows-latest  # Use Windows runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        choco install jq
    - name: Set WinRM Password
      run: echo "WINRM_PASSWORD=${{ secrets.EC2_PASSWORD }}" >> $GITHUB_ENV
    - name: Print EC2_HOST
      run: echo "EC2_HOST=${{ secrets.EC2_HOST }}"
    - name: Print EC2_USER
      run: echo "EC2_USER=${{ secrets.EC2_USER }}"
    - name: Ensure directories exist and determine target directory
      id: determine-directory
      shell: pwsh
      run: |
        $session = New-PSSession -ComputerName ${{ secrets.EC2_HOST }} -Credential (New-Object PSCredential('${{ secrets.EC2_USER }}', (ConvertTo-SecureString '${{ secrets.EC2_PASSWORD }}' -AsPlainText -Force))) -Port ${{ secrets.EC2_PORT }} -UseSSL -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck)
        Invoke-Command -Session $session -ScriptBlock {
          $bluePath = "C:\websites\zPax-Test-Portal-blue"
          $greenPath = "C:\websites\zPax-Test-Portal-green"
          if (-Not (Test-Path $bluePath)) { New-Item -ItemType Directory -Path $bluePath }
          if (-Not (Test-Path $greenPath)) { New-Item -ItemType Directory -Path $greenPath }
          if (Test-Path $bluePath) {
            return "zPax-Test-Portal-green"
          } else {
            return "zPax-Test-Portal-blue"
          }
        } -ArgumentList $null -OutVariable targetDirectory
        echo "target_directory=$($targetDirectory.Trim().Replace('return', '').Trim())" >> $GITHUB_ENV
        Remove-PSSession -Session $session
    - name: Extract files and configure IIS
      shell: pwsh
      run: |
        $session = New-PSSession -ComputerName ${{ secrets.EC2_HOST }} -Credential (New-Object PSCredential('${{ secrets.EC2_USER }}', (ConvertTo-SecureString '${{ secrets.EC2_PASSWORD }}' -AsPlainText -Force))) -Port ${{ secrets.EC2_PORT }} -UseSSL -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck)
        Invoke-Command -Session $session -ScriptBlock {
          cd C:\websites\${{ env.target_directory }}
          tar -xzvf publish.tar.gz
          Remove-Item publish.tar.gz
          Import-Module WebAdministration
          if ((Get-WebSite -Name "zPax-Test-Portal").PhysicalPath -eq "C:\websites\zPax-Test-Portal-blue") {
            Set-ItemProperty "IIS:\Sites\zPax-Test-Portal" -name physicalPath -value "C:\websites\zPax-Test-Portal-green"
          } else {
            Set-ItemProperty "IIS:\Sites\zPax-Test-Portal" -name physicalPath -value "C:\websites\zPax-Test-Portal-blue"
          }
          Restart-WebAppPool -Name "zPax-Test-Portal"
        }
        Remove-PSSession -Session $session
    - name: Complete job
      run: echo "Deployment completed."
